<a href="https://colab.research.google.com/github/sangramdhurve/Data-science/blob/main/Practical_of_Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Numpy 



## Arrays

In [1]:
from numpy import *
# Single dimensional array 
array_data1 = [1.4, 7, 8, 12.3]
array1 = array(array_data1)
print("Array 1 : ",array1)

Array 1 :  [ 1.4  7.   8.  12.3]


In [2]:
# Multi dimensional array 
#
array_data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
array2 = array(array_data2)
print("Array 2: ", array2)

Array 2:  [[1 2 3 4]
 [5 6 7 8]]


In [3]:
# Check the Dimension of the array 
print("Dimension of array2 is ",array2.ndim)

# Check the Size of Array 
print("Shape of array2 is ",array2.shape)

Dimension of array2 is  2
Shape of array2 is  (2, 4)


In [4]:
# Create and array of zeros 
Zero_Array = zeros((3, 6))
print("Zero Array",Zero_Array)


Zero Array [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [5]:
# Check Data Type of Array 
array_data1 = [1,2,3,4]
Array1 = array(array_data1)
print("data type of Array1 is : ",Array1.dtype)

data type of Array1 is :  int64



### Arrays and Scalars 

### Notes:1)  Operations between Arrays of same size happens element wise 
### Notes:2)  Operations with Arrays and Scalars will propagate to each element 


In [6]:
#--------------------
# ELement wise array multiplication 
#--------------------
arr1 = array([[1,2,3],[4,5,6]])
arr2 = arr1*arr1 
print("Original Array ",arr1)
print("Element wise sq of arr1 is : ",arr2)
arr3 = arr1*2
print("Double array element wise", arr3)

Original Array  [[1 2 3]
 [4 5 6]]
Element wise sq of arr1 is :  [[ 1  4  9]
 [16 25 36]]
Double array element wise [[ 2  4  6]
 [ 8 10 12]]


In [7]:
#--------------------------------------------
# Indexing and slicing of arrays 
#--------------------------------------------
# Define Array of 10 elements 
Arr1 = array(arange(10))
print("Arr1 before manipulation is :",Arr1)


# Choose Index pos 3 to 5 and create a sub array 
# Note the 5th Index position actually does not get selected 
# Note: Only elemenst upto the 5th position get selected 
Sub_Arr1 = Arr1[3:5]
# Display elements of sub array 
print("Sub_Array before change is:",Sub_Arr1)


# Assign a fixed value to sub Array Index Pos 0 
Sub_Arr1[0] = 56
# Display elements of Sub_Arr1
print("Sub Array after change :",Sub_Arr1)



# Display elements of original array 
# Note: change in sub Array caused change in main array 
print("Original Array is",Arr1)



# Assign a element to the entire Sub array 
Sub_Arr1 = 66
# Display Sub Arry 
print("Sub Array after new assign is : ",Sub_Arr1)


# Display main Array 
print("Main Array after new assign is : ", Arr1)


Arr1 before manipulation is : [0 1 2 3 4 5 6 7 8 9]
Sub_Array before change is: [3 4]
Sub Array after change : [56  4]
Original Array is [ 0  1  2 56  4  5  6  7  8  9]
Sub Array after new assign is :  66
Main Array after new assign is :  [ 0  1  2 56  4  5  6  7  8  9]


In [8]:
# Boolean Indexing 
#-------------------------------
# Create an Array of names 
Arr_Names = array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])


# Get Array size
Arrsize = Arr_Names.shape
Len1 = Arrsize[0]


# Create a  Vector of random numbers of the same length
# Init a  Vector of size = Len1 
Rand_Set = array(arange(Len1))


# Populate Vector with Random nos from 1 to 10 
for i in range(Len1):
    Rand_Set[i-1] = random.uniform(1,10)
    
# Display Rand Vector
print("Rand Vector",Rand_Set)


# Get Those Index positions for which name = Bob 
# Use the index set to choose a sub set of Random Numbers 
Match_name_rand = Rand_Set[Arr_Names == 'Bob']
print("Matching Sub set of Rand Num is:",Match_name_rand)

Rand Vector [2 3 2 8 6 3 6]
Matching Sub set of Rand Num is: [2 8]


### Array  Operations 

In [9]:
# Slicing multi dimensional Arrays 
# define a 3 by 4 array 
Array1 = array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Original Array is ", Array1)
Array_Slice1 = Array1[2,:2]
print("Sliced Array is : ",Array_Slice1)


Original Array is  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced Array is :  [ 9 10]


In [10]:
#-------------
# Square Root 
#-------------
from numpy import *
Arr = arange(10)
Sqrt_Arr = sqrt(Arr)
print("Sqrt Root values:", Sqrt_Arr )

Sqrt Root values: [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [11]:
#--------------------------
# Binary Function example 
#---------------------------

# Create Two Arrays of 10 random numbers each 
x = random.randn(10)
y = random.randn(10)
# Print  both the arrays 
print("X Array is :", x)
print("Y Array is :", y)
# Get the Element wise max, comparing both arrays 
Max_XY = maximum(x,y)
print("The Max element wise is :", Max_XY)

X Array is : [-0.94174255  0.39559307 -2.31536509  0.56477493 -0.0891912   0.25215679
  0.60244749  0.00555628  0.07408158  0.23918975]
Y Array is : [-1.24538566 -0.90968992  0.73564421  1.75832064  1.1735916   0.36997479
 -1.29252465  0.15647224  1.0415769  -0.72310463]
The Max element wise is : [-0.94174255  0.39559307  0.73564421  1.75832064  1.1735916   0.36997479
  0.60244749  0.15647224  1.0415769   0.23918975]


In [12]:
 # Conditional logic as Array Operators
# ---
# Define Boolean Array 
Bool_Arr = array([True,False,True,False,True])
X_Arr = array([1,2,3,4,5])
Y_Arr = array([10,20,30,40,50])

Choice = [(X if Z else Y) for X,Y,Z in zip(X_Arr,Y_Arr,Bool_Arr)]
print("Choice: ",Choice)

Choice:  [1, 20, 3, 40, 5]


In [13]:
#---------------------------------
# The where clause in arrays 
#---------------------------------
# Create a 3x3 array of random numbers 
Arr3 = random.randn(3,3)
print("original  Array is : ", Arr3)
# Replace pos numbers with +2 and _ve nos with -2 
Arr3_Chg = where(Arr3 > 0, 2, -2)
# Print changed Array 
print("Chg Array is : ", Arr3_Chg)

original  Array is :  [[ 1.61501331  0.32028214 -0.71915144]
 [ 0.47563018  1.35404155  0.74659394]
 [-0.36831859  1.76843875  0.38403077]]
Chg Array is :  [[ 2  2 -2]
 [ 2  2  2]
 [-2  2  2]]


###  Basic Statistical functions 

In [14]:
Arr_Stat = array([[1,2,3],[4,5,6],[7,8,9]])
# Mean
Arr_Mean = mean(Arr_Stat) 
print("Mean of Array is: ",Arr_Mean)

Mean of Array is:  5.0


In [15]:
# Sum 
Arr_Sum = sum(Arr_Stat)
print("Sum of Array is:",Arr_Sum)

Sum of Array is: 45


In [16]:

# Get Column means (0th dimension or axis )
Arr_Mean_Cols = Arr_Stat.mean(0)
print("Col_Means = :", Arr_Mean_Cols)


Col_Means = : [4. 5. 6.]


### Misc  Array operations 

In [17]:
#--------------------------------------------
#   Sorting 
#--------------------------------------------
Arr4 = array([10,2,34,5])
Arr4_Sorted = sorted(Arr4) 
print("Unsorted Array is ",Arr4)
print("Sorted Array is ",Arr4_Sorted)


Unsorted Array is  [10  2 34  5]
Sorted Array is  [2, 5, 10, 34]


In [18]:
#-------------------------------------------------
#  Unique  and other Array set operations 
#-------------------------------------------------
# Create a Names Array 
Names_Arr = array(["Jim","Bob","Roy","Rajesh","Roy","Kumar","Jeet","Roy","Joy"])
# Get Unique Names 
Names_Arr_Unq = unique(Names_Arr)
print("Unique Names are ",Names_Arr_Unq)

Unique Names are  ['Bob' 'Jeet' 'Jim' 'Joy' 'Kumar' 'Rajesh' 'Roy']


In [19]:
# Generate a 4 by 4  Array of random numbers following 
# Normal distribution 
#------------------------------------------------------
Arr4by4 = random.normal(size=(4,4))
print(Arr4by4)

[[ 0.28167023  0.18257743  1.238949   -0.59805922]
 [-0.42729929 -0.67620013  0.18867787  1.79010237]
 [ 0.85338755 -0.35574622  0.76131426 -0.88333992]
 [ 1.02202408  2.10121664 -1.42461359  1.59400153]]


### End of Module - Numpy